module.exports = {
  REGISTERED: "REGISTERED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  ESTIMATE_SHARED: "ESTIMATE_SHARED",
  CUSTOMER_APPROVED: "CUSTOMER_APPROVED",
  READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
  COMPLETED: "COMPLETED",
};
